import { GoogleGenerativeAI } from "@google/generative-ai";

const apiKey = process.env.EXPO_PUBLIC_GOOGLE_GEMINI_RANDOM_PLACES_KEY;

if (!apiKey) {
  throw new Error("Missing Gemini API key");
}

const genAI = new GoogleGenerativeAI(apiKey);

export const model = genAI.getGenerativeModel({
  model: "gemini-2.5-flash",
});

export const generationConfig = {
  temperature: 1,
  topP: 0.95,
  topK: 64,
  maxOutputTokens: 8192,
  responseMimeType: "application/json",
};

export const chatSession = model.startChat({
  generationConfig,
  history: [
    {
      role: 'user',
      parts: [
        {
          text: `Return ONLY valid JSON array of 10 RANDOM famous travel places. Make sure results are different each time.Include placeName, placeImageUrl, description, capitalCity, country.`,
        },
      ],
    },
    {
      role: 'model',
      parts: [
        {
          text: JSON.stringify([
            {
              placeName: "Eiffel Tower",
              placeImageUrl: "https://images.unsplash.com/photo-1511739001486-6bfe10ce785f",
              description: "An iconic iron lattice tower on the Champ de Mars, symbol of France and global cultural icon.",
              capitalCity: "Paris",
              country: "France",
            },
            {
              placeName: "Machu Picchu",
              placeImageUrl: "https://images.unsplash.com/photo-1587590227264-0ac64ce63ce8",
              description: "A 15th-century Inca citadel located in the Eastern Cordillera of southern Peru on a mountain ridge.",
              capitalCity: "Lima",
              country: "Peru",
            },
            {
              placeName: "Grand Canyon",
              placeImageUrl: "https://images.unsplash.com/photo-1474044159687-1ee9f3a51722",
              description: "A massive canyon carved by the Colorado River, known for its visually overwhelming size and intricate landscapes.",
              capitalCity: "Washington, D.C.",
              country: "USA",
            },
            {
              placeName: "Great Wall of China",
              placeImageUrl: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d",
              description: "An ancient series of walls and fortifications built across the historical northern borders of ancient Chinese states.",
              capitalCity: "Beijing",
              country: "China",
            },
            {
              placeName: "Santorini",
              placeImageUrl: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff",
              description: "Famous for its white-washed buildings with blue domes, stunning sunsets, and volcanic landscapes.",
              capitalCity: "Athens",
              country: "Greece",
            },
            {
              placeName: "Colosseum",
              placeImageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5",
              description: "The largest ancient amphitheatre ever built, located in the center of the city of Rome.",
              capitalCity: "Rome",
              country: "Italy",
            },
            {
              placeName: "Taj Mahal",
              placeImageUrl: "https://images.unsplash.com/photo-1564507592333-c60657eea523",
              description: "An ivory-white marble mausoleum on the right bank of the river Yamuna, a masterpiece of Muslim art.",
              capitalCity: "New Delhi",
              country: "India",
            },
            {
              placeName: "Great Barrier Reef",
              placeImageUrl: "https://images.unsplash.com/photo-1582967788606-a171c1080cb0",
              description: "The world's largest coral reef system, composed of over 2,900 individual reefs and 900 islands.",
              capitalCity: "Canberra",
              country: "Australia",
            },
            {
              placeName: "Pyramids of Giza",
              placeImageUrl: "https://images.unsplash.com/photo-1503177119275-0aa32b3a9368",
              description: "Ancient pyramid structures located on the Giza plateau, the oldest of the Seven Wonders of the Ancient World.",
              capitalCity: "Cairo",
              country: "Egypt",
            },
            {
              placeName: "Kyoto Temples",
              placeImageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e",
              description: "Famous for its classical Buddhist temples, gardens, imperial palaces, and traditional wooden houses.",
              capitalCity: "Tokyo",
              country: "Japan",
            },
            {
              placeName: "Banff National Park",
              placeImageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
              description: "Canada's oldest national park, located in the Rocky Mountains with turquoise glacial lakes.",
              capitalCity: "Ottawa",
              country: "Canada",
            },
            {
              placeName: "Stonehenge",
              placeImageUrl: "https://images.unsplash.com/photo-1599408162449-003666f06a9d",
              description: "A prehistoric monument in Wiltshire, consisting of a ring of standing stones each around 13 feet high.",
              capitalCity: "London",
              country: "United Kingdom",
            },
            {
              placeName: "Christ the Redeemer",
              placeImageUrl: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92",
              description: "An Art Deco statue of Jesus Christ in Rio de Janeiro, overlooking the city from Mount Corcovado.",
              capitalCity: "Brasilia",
              country: "Brazil",
            },
            {
              placeName: "Petra",
              placeImageUrl: "https://images.unsplash.com/photo-1579606030126-d30231aa8dee",
              description: "A historical and archaeological city in southern Jordan, famous for its rock-cut architecture.",
              capitalCity: "Amman",
              country: "Jordan",
            },
            {
              placeName: "Angkor Wat",
              placeImageUrl: "https://images.unsplash.com/photo-1500835556837-99ac94a94552",
              description: "A massive Buddhist temple complex located in northern Cambodia, the largest religious monument in the world.",
              capitalCity: "Phnom Penh",
              country: "Cambodia",
            },
            {
              placeName: "Serengeti National Park",
              placeImageUrl: "https://images.unsplash.com/photo-1516426122078-c23e76319801",
              description: "A massive African ecosystem famous for its huge herds of wildebeest and zebras and for its lion population.",
              capitalCity: "Dodoma",
              country: "Tanzania",
            },
            {
              placeName: "Burj Khalifa",
              placeImageUrl: "https://images.unsplash.com/photo-1526495124232-a02e18494d17",
              description: "The world's tallest building, located in Dubai, offering breathtaking views of the city and desert.",
              capitalCity: "Abu Dhabi",
              country: "United Arab Emirates",
            },
            {
              placeName: "Hagia Sophia",
              placeImageUrl: "https://images.unsplash.com/photo-1543967625-7033be9f727c",
              description: "An architectural marvel in Istanbul, originally a Byzantine church, then a mosque, and now a museum and mosque.",
              capitalCity: "Ankara",
              country: "Turkey",
            },
            {
              placeName: "Cliffs of Moher",
              placeImageUrl: "https://images.unsplash.com/photo-1500622345596-ec6bb3be4bc8",
              description: "Sea cliffs located at the southwestern edge of the Burren region in County Clare, Ireland.",
              capitalCity: "Dublin",
              country: "Ireland",
            },
            {
              placeName: "Sagrada Família",
              placeImageUrl: "https://images.unsplash.com/photo-1583778175782-d1d704d4aee8",
              description: "A large unfinished Roman Catholic minor basilica in Barcelona, designed by Antoni Gaudí.",
              capitalCity: "Madrid",
              country: "Spain",
            },
            {
              placeName: "Swiss Alps",
              placeImageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b",
              description: "Spectacular mountain range known for skiing, hiking, and picturesque alpine villages.",
              capitalCity: "Bern",
              country: "Switzerland",
            },
            {
              placeName: "Ha Long Bay",
              placeImageUrl: "https://images.unsplash.com/photo-1528127269322-539801943592",
              description: "Emerald waters and thousands of towering limestone islands topped by rainforests.",
              capitalCity: "Hanoi",
              country: "Vietnam",
            },
            {
              placeName: "Iguazu Falls",
              placeImageUrl: "https://images.unsplash.com/photo-1580222166699-2a9c17757999",
              description: "The largest waterfall system in the world, located on the border of Argentina and Brazil.",
              capitalCity: "Buenos Aires",
              country: "Argentina",
            },
            {
              placeName: "Mount Fuji",
              placeImageUrl: "https://images.unsplash.com/photo-1490806678282-2d4d187762a9",
              description: "Japan's highest mountain and an iconic active volcano, a sacred site and source of artistic inspiration.",
              capitalCity: "Tokyo",
              country: "Japan",
            },
            {
              placeName: "Louvre Museum",
              placeImageUrl: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a",
              description: "The world's largest art museum and a historic monument in Paris, home to the Mona Lisa.",
              capitalCity: "Paris",
              country: "France",
            },
            {
              placeName: "Acropolis of Athens",
              placeImageUrl: "https://images.unsplash.com/photo-1555992336-fb0d29498b13",
              description: "An ancient citadel located on a rocky outcrop above the city of Athens, containing the Parthenon.",
              capitalCity: "Athens",
              country: "Greece",
            },
            {
              placeName: "Chichén Itzá",
              placeImageUrl: "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a",
              description: "A large pre-Columbian city built by the Maya people of the Terminal Classic period.",
              capitalCity: "Mexico City",
              country: "Mexico",
            },
            {
              placeName: "Galápagos Islands",
              placeImageUrl: "https://images.unsplash.com/photo-1548432571-066367761044",
              description: "An archipelago of volcanic islands distributed on either side of the equator in the Pacific Ocean.",
              capitalCity: "Quito",
              country: "Ecuador",
            },
            {
              placeName: "Times Square",
              placeImageUrl: "https://images.unsplash.com/photo-1534430480872-3498386e7a55",
              description: "A major commercial intersection, tourist destination, and entertainment center in Midtown Manhattan.",
              capitalCity: "Washington, D.C.",
              country: "USA",
            },
            {
              placeName: "Blue Lagoon",
              placeImageUrl: "https://images.unsplash.com/photo-1520106212299-d99c443e4568",
              description: "A geothermal spa in southwestern Iceland, known for its milky-blue silica-rich waters.",
              capitalCity: "Reykjavik",
              country: "Iceland",
            },
            {
              placeName: "Amalfi Coast",
              placeImageUrl: "https://images.unsplash.com/photo-1533105079780-92b9be482077",
              description: "A stretch of coastline in southern Italy, known for its rugged shoreline and pastel-colored villages.",
              capitalCity: "Rome",
              country: "Italy",
            },
            {
              placeName: "Table Mountain",
              placeImageUrl: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99",
              description: "A flat-topped mountain forming a prominent landmark overlooking the city of Cape Town.",
              capitalCity: "Pretoria",
              country: "South Africa",
            },
            {
              placeName: "Victoria Falls",
              placeImageUrl: "https://images.unsplash.com/photo-1492321497455-4209b1c1105e",
              description: "One of the world's largest waterfalls, located on the Zambezi River at the border between Zambia and Zimbabwe.",
              capitalCity: "Lusaka",
              country: "Zambia",
            },
            {
              placeName: "Bora Bora",
              placeImageUrl: "https://images.unsplash.com/photo-1500313830540-7b6650a74fd0",
              description: "A small South Pacific island northwest of Tahiti, known for its turquoise lagoons and overwater bungalows.",
              capitalCity: "Papeete",
              country: "French Polynesia",
            },
            {
              placeName: "Prague Castle",
              placeImageUrl: "https://images.unsplash.com/photo-1517329782449-810562a4ec2f",
              description: "A castle complex in Prague, the official office of the President of the Czech Republic.",
              capitalCity: "Prague",
              country: "Czech Republic",
            },
            {
              placeName: "Neuschwanstein Castle",
              placeImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91764c9942",
              description: "A 19th-century Romanesque Revival palace on a rugged hill, the inspiration for Disney's Sleeping Beauty castle.",
              capitalCity: "Berlin",
              country: "Germany",
            },
            {
              placeName: "Plitvice Lakes National Park",
              placeImageUrl: "https://images.unsplash.com/photo-1444464666168-49d633b867ad",
              description: "A world-renowned park with 16 terraced lakes, joined by waterfalls, extending into a limestone canyon.",
              capitalCity: "Zagreb",
              country: "Croatia",
            },
            {
              placeName: "Mount Everest",
              placeImageUrl: "https://images.unsplash.com/photo-1544735716-392fe2489ffa",
              description: "Earth's highest mountain above sea level, located in the Mahalangur Himal sub-range of the Himalayas.",
              capitalCity: "Kathmandu",
              country: "Nepal",
            },
            {
              placeName: "Forbidden City",
              placeImageUrl: "https://images.unsplash.com/photo-1542385151-efd9000785a0",
              description: "A palace complex in central Beijing, China, formerly the former Chinese imperial palace.",
              capitalCity: "Beijing",
              country: "China",
            },
            {
              placeName: "Moscow Kremlin",
              placeImageUrl: "https://images.unsplash.com/photo-1513326738677-b964603b136d",
              description: "A fortified complex at the heart of Moscow, overlooking the Moskva River and Red Square.",
              capitalCity: "Moscow",
              country: "Russia",
            },
            {
              placeName: "Chefchaouen",
              placeImageUrl: "https://images.unsplash.com/photo-1548013146-72479768bbaa",
              description: "The famous blue city of Morocco, known for its buildings in shades of blue in the Rif Mountains.",
              capitalCity: "Rabat",
              country: "Morocco",
            },
            {
              placeName: "Easter Island",
              placeImageUrl: "https://images.unsplash.com/photo-1512411441329-8758833980d9",
              description: "A remote volcanic island in Polynesia, famous for archaeological sites including nearly 900 monumental statues called moai.",
              capitalCity: "Santiago",
              country: "Chile",
            },
            {
              placeName: "Buckingham Palace",
              placeImageUrl: "https://images.unsplash.com/photo-1529655683826-aba9b3e77383",
              description: "The London residence and administrative headquarters of the monarch of the United Kingdom.",
              capitalCity: "London",
              country: "United Kingdom",
            },
            {
              placeName: "Uluru (Ayers Rock)",
              placeImageUrl: "https://images.unsplash.com/photo-1524338198850-8a2ff63aaceb",
              description: "A large sandstone rock formation in the southern part of the Northern Territory in central Australia.",
              capitalCity: "Canberra",
              country: "Australia",
            },
            {
              placeName: "Marina Bay Sands",
              placeImageUrl: "https://images.unsplash.com/photo-1525625239512-46cc2ebad241",
              description: "An integrated resort fronting Marina Bay in Singapore, featuring an iconic infinity pool on the roof.",
              capitalCity: "Singapore",
              country: "Singapore",
            },
            {
              placeName: "Palace of Versailles",
              placeImageUrl: "https://images.unsplash.com/photo-1585145802280-92900a6e026c",
              description: "The principal royal residence of France from 1682 until the French Revolution.",
              capitalCity: "Paris",
              country: "France",
            },
            {
              placeName: "Zion National Park",
              placeImageUrl: "https://images.unsplash.com/photo-1469474968028-56623f02e42e",
              description: "A southwest Utah nature preserve distinguished by Zion Canyon's steep red cliffs.",
              capitalCity: "Washington, D.C.",
              country: "USA",
            },
            {
              placeName: "Hallstatt",
              placeImageUrl: "https://images.unsplash.com/photo-1527661591475-527312dd65f5",
              description: "A mountain village on Lake Hallstatt's western shore, known for its salt mines and stunning views.",
              capitalCity: "Vienna",
              country: "Austria",
            },
            {
              placeName: "Jeju Island",
              placeImageUrl: "https://images.unsplash.com/photo-1533035353720-f1c6a75cd8ab",
              description: "Known for its beach resorts and volcanic landscape of craters and cavelike lava tubes.",
              capitalCity: "Seoul",
              country: "South Korea",
            },
            {
              placeName: "Fiordland National Park",
              placeImageUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800",
              description: "Home to the glacier-carved fiords of Milford and Doubtful Sounds, showcasing dramatic mountain scenery.",
              capitalCity: "Wellington",
              country: "New Zealand",
            },
          ]),
        },
      ],
    },
  ],
});